openapi: 3.0.3
info:
  title: ArgentBank
  description:  API Document for transactions.
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
tags:
  - name: Transaction
    description: Everything about transactions
paths:
  /transaction:
    get:
      tags:
        - Transaction
      summary: Retrieve transactions
      description: Retrieve all transactions
      operationId: getTransaction
      parameters:
        - in: query
          name: Id
          description: Account ID
          required: true
          schema:
            type: string
        - in: query
          name: month
          description: Month of the transaction
          required: false
          schema:
            type: string
            minimum: 1
            maximum: 12
        - in: query
          name: year
          description: Year of the transaction
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid status value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []
    put:
      tags:
        - transaction
      summary: Modify transactions
      description: Modify transactions by their ID
      operationId: updateTransaction
      parameters:
        - in: query
          name: id
          description: transaction ID
          required: true
          schema:
            type: string
      requestBody:
        description: Modify an existing transaction in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editTransaction'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []
    post:
      tags:
        - transaction
      summary: Add a new transaction
      description: Add a new transaction to the store
      operationId: addTransaction
      requestBody:
        description: Create a new transaction in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses :
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Transaction'
        '405':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []
    delete:
      tags:
        - transaction
      summary: Deletes a transaction
      description: delete a transaction
      operationId: deleteTransaction
      parameters:
        - in: query
          name: id
          description: transactionId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successfull
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: Id of the deleted transaction
        '400':
          description: Invalid transaction value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []
  /transaction/{id} :
    get:
      tags:
        - transaction
      summary: Find transaction by ID
      description: Returns a single transaction
      operationId: getTransactionById
      parameters:
        - in: path
          name: id
          description: ID of transaction to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: transaction not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - bearerAuth: []
components:
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  schemas:
    Transaction:
      properties:
        description:
          type: string
          description: transaction description
        amount:
          type: number
          description: amount of money used in the transaction
        balance:
          type: number
          description: account balance after transaction
        type:
          type: string
          description: transaction type
        category:
          type: string
          description: transaction category
        notes:
          type: string
          description: transaction notes
    Category:
      properties:
        id:
          type: integer
          description: category ID
        label:
          type: string
          description: category label
    editTransaction:
      properties:
        categoryID:
          type: integer
          description: category ID
        notes:
          type: string
          description: transaction notes
    Error:
      properties:
        status:
          type: number
          description: Error Code
        message:
          type: string
          description: Error Message
        endpoint:
          type: string
          description: Api Endpoint
        resource:
          type: number
          description: ID of the resource the endpoint is trying to reach